### ISSUE TITLE
Build UI Library

### ISSUE THREAD

**Issue by innopoop** [novaforgood/RISC-Frontend#1]
Assign yourself and comment with whichever task you take up!
~~1. Buttons~~
~~2. Cards~~
~~3. Text~~
~~4. Single Line Input~~
5. Text Areas
6. Tags
7. Toggles
8. Checkboxes
10. Error Text
11. Modal

**Comment by alyssamw** [comment]
Starting Modal

**Comment by NikhilSuresh24** [comment]
Working on Modal
