### ISSUE TITLE
Theme Discussion

### ISSUE THREAD

**Issue by innopoop** [novaforgood/RISC-Frontend#10]
This video on CSS Variables is a really good [https://www.youtube.com/watch?v=MAtaT8BZEAo](https://www.youtube.com/watch?v=MAtaT8BZEAo) starting point but if you would like to see alternative methods of implementing it, [https://dev.to/ohitslaurence/creating-dynamic-themes-with-react-tailwindcss-59cl](https://dev.to/ohitslaurence/creating-dynamic-themes-with-react-tailwindcss-59cl) is another resource (although the video is a lot better imo).

The items that we might want to be customizable by theme:

1. Base Color
2. Hover Color
3. Active Color
4. Disabled (Could just be Opacity tbh)
5. Error Color

**Comment by hcsong213** [comment]
I'll try to connect a json object with the data to the css of a sample page.
