### ISSUE TITLE
Booking a Chat pages

### ISSUE THREAD

**Issue by innopoop** [novaforgood/RISC-Frontend#26]
[figma screens](https://www.figma.com/file/qfzd9rev3yhzKeCZBv8lIB/?node-id=3086%3A13314)  
Deadline: 6/4

Blocked by:
1. Mentor/Mentee Display & Book a chat button #29 
2. getChatsByUser
3. Modal [Modal on a modal??] #1 
  
Things to get done:  
1. Display of Calendar, Current Month, grayed out dates if in the past, non-grayed out dates if in the future, and darkened date if selected
2. Hover: Possibly have a hover feature where if you hover over a selectable date, it gives you a preview of available times instead of needing to click into it

**Comment by alyssamw** [comment]
skeleton on bookAChat branch, will rely on Modal component and some backend queries for getting chats

**Comment by innopoop** [comment]
> skeleton on bookAChat branch, will rely on Modal component and some backend queries for getting chats  

@NikhilSuresh24 is currently working on modal, and do you know which specific queries you would need?

**Comment by alyssamw** [comment]
Something along the lines of getChatsByUser?

I didn't see an entity for Chats in the backend repo yet though, so maybe I'm misunderstanding it. Def lower prio than the other entities
