### ISSUE TITLE
Program Switching logic

### ISSUE THREAD

**Issue by innopoop** [novaforgood/RISC-Frontend#28]
[figma here](https://www.figma.com/file/qfzd9rev3yhzKeCZBv8lIB/wireframe?node-id=2270%3A0)
Deadline: N/A

Questions:
1. Think through how we want to store and cache program data/program member data when we end up switching to and from programs => bring it up for discussion
2. Is the [program switching styling](https://www.figma.com/file/qfzd9rev3yhzKeCZBv8lIB/wireframe?node-id=1727%3A2866) still the same as before? @serene-sup 
  ![image](https://user-images.githubusercontent.com/20727715/119891156-89998b80-beed-11eb-8360-3a6dd97292dd.png)
  ![image](https://user-images.githubusercontent.com/20727715/119891274-9fa74c00-beed-11eb-9b49-b1b87e887db9.png)
3. [Location of profile picture personal settings portion](https://www.figma.com/file/qfzd9rev3yhzKeCZBv8lIB/wireframe?node-id=3090%3A11972)

**Comment by legitmaxwu** [comment]
Done in #53
