### ISSUE TITLE
Join Mentorship Program Logic

### ISSUE THREAD

**Issue by innopoop** [novaforgood/RISC-Frontend#31]
There are two parts to this- the one we want to take care of is simply the action of joining (click a button while logged in and afterwards you should be a part of some program)

The second part of this logic would be implementing the join via invite link vs join via homepage logic which is unable to be completed as of now  

Potential Blocks:
1. Invite links
2. Public-facing homepage of a program #25 

Things to be done:
1. /join
2. Action of joining a program **when logged in**

**Comment by hcsong213** [comment]
Starting this

**Comment by hcsong213** [comment]
I'll start the chain beginning here: https://www.figma.com/file/qfzd9rev3yhzKeCZBv8lIB/wireframe?node-id=2382%3A2643
